package cpu;
import java.util.HashMap;

public class FastInstructionsAdder {

	public static void addInstructions(HashMap<Integer, String[][]> opcodeToInstruction) {
		String[][] x00 = {{"NOP"}};
		String[][] x01 = {{"read_lsb"},{"read_msb"},{"fetch","write_r16_n16(BC)"}};
		String[][] x02 = {{"write_r8_r8((BC),A)"},{"fetch"}};
		String[][] x03 = {{"increment_r16(BC)"},{"fetch"}};
		String[][] x04 = {{"fetch","increment_r8(B)"}};
		String[][] x05 = {{"fetch","decrement_r8(B)"}};
		String[][] x06 = {{"read_lsb"},{"fetch","write_r8_n8(B)"}};
		String[][] x07 = {{"RLCA","fetch"}};
		String[][] x08 = {{"read_lsb"},{"read_msb"},{"write_abs_n16_lsb(SP)","increment_n16"},{"write_abs_n16_msb(SP)"},{"fetch"}};
		String[][] x09 = {{"ADD_HL_r16(BC)"},{"fetch"}};
		String[][] x0A = {{"write_r8_r8(A,(BC))"},{"fetch"}};
		String[][] x0B = {{"decrement_r16(BC)"},{"fetch"}};
		String[][] x0C = {{"fetch","increment_r8(C)"}};
		String[][] x0D = {{"fetch","decrement_r8(C)"}};
		String[][] x0E = {{"read_lsb"},{"fetch","write_r8_n8(C)"}};
		String[][] x0F = {{"RRCA","fetch"}};
		String[][] x10 = {{"STOP","fetch"}};
		String[][] x11 = {{"read_lsb"},{"read_msb"},{"fetch","write_r16_n16(DE)"}};
		String[][] x12 = {{"write_r8_r8((DE),A)"},{"fetch"}};
		String[][] x13 = {{"increment_r16(DE)"},{"fetch"}};
		String[][] x14 = {{"fetch","increment_r8(D)"}};
		String[][] x15 = {{"fetch","decrement_r8(D)"}};
		String[][] x16 = {{"read_lsb"},{"fetch","write_r8_n8(D)"}};
		String[][] x17 = {{"RLA","fetch"}};
		String[][] x18 = {{"read_lsb"},{"JR_e8"},{"fetch"}};
		String[][] x19 = {{"ADD_HL_r16(DE)"},{"fetch"}};
		String[][] x1A = {{"write_r8_r8(A,(DE))"},{"fetch"}};
		String[][] x1B = {{"decrement_r16(DE)"},{"fetch"}};
		String[][] x1C = {{"fetch","increment_r8(E)"}};
		String[][] x1D = {{"fetch","decrement_r8(E)"}};
		String[][] x1E = {{"read_lsb"},{"fetch","write_r8_n8(E)"}};
		String[][] x1F = {{"RRA","fetch"}};
		String[][] x20 = {{"read_lsb","checkCondition(NZ)"},{"JR_e8"},{"fetch"}};
		String[][] x21 = {{"read_lsb"},{"read_msb"},{"fetch","write_r16_n16(HL)"}};
		String[][] x22 = {{"write_r8_r8((HL),A)","increment_r16(HL)"},{"fetch"}};
		String[][] x23 = {{"increment_r16(HL)"},{"fetch"}};
		String[][] x24 = {{"fetch","increment_r8(H)"}};
		String[][] x25 = {{"fetch","decrement_r8(H)"}};
		String[][] x26 = {{"read_lsb"},{"fetch","write_r8_n8(H)"}};
		String[][] x27 = {{"DAA","fetch"}};
		String[][] x28 = {{"read_lsb","checkCondition(Z)"},{"JR_e8"},{"fetch"}};
		String[][] x29 = {{"ADD_HL_r16(HL)"},{"fetch"}};
		String[][] x2A = {{"save_r8((HL))","increment_r16(HL)"},{"fetch","write_r8_n8(A)"}};
		String[][] x2B = {{"decrement_r16(HL)"},{"fetch"}};
		String[][] x2C = {{"fetch","increment_r8(L)"}};
		String[][] x2D = {{"fetch","decrement_r8(L)"}};
		String[][] x2E = {{"read_lsb"},{"fetch","write_r8_n8(L)"}};
		String[][] x2F = {{"CPL","fetch"}};
		String[][] x30 = {{"read_lsb","checkCondition(NC)"},{"JR_e8"},{"fetch"}};
		String[][] x31 = {{"read_lsb"},{"read_msb"},{"fetch","write_r16_n16(SP)"}};
		String[][] x32 = {{"write_r8_r8((HL),A)","decrement_r16(HL)"},{"fetch"}};
		String[][] x33 = {{"increment_r16(SP)"},{"fetch"}};
		String[][] x34 = {{"save_r8((HL))"},{"increment_r8(saved)"},{"fetch"}};
		String[][] x35 = {{"save_r8((HL))"},{"decrement_r8(saved)"},{"fetch"}};
		String[][] x36 = {{"read_lsb"},{"write_r8_n8((HL))"},{"fetch"}};
		String[][] x37 = {{"SCF","fetch"}};
		String[][] x38 = {{"read_lsb","checkCondition(C)"},{"JR_e8"},{"fetch"}};
		String[][] x39 = {{"ADD_HL_r16(SP)"},{"fetch"}};
		String[][] x3A = {{"save_r8((HL))","decrement_r16(HL)"},{"fetch","write_r8_n8(A)"}};
		String[][] x3B = {{"decrement_r16(SP)"},{"fetch"}};
		String[][] x3C = {{"fetch","increment_r8(A)"}};
		String[][] x3D = {{"fetch","decrement_r8(A)"}};
		String[][] x3E = {{"read_lsb"},{"fetch","write_r8_n8(A)"}};
		String[][] x3F = {{"CCF","fetch"}};
		String[][] x40 = {{"fetch","write_r8_r8(B,B)"}};
		String[][] x41 = {{"fetch","write_r8_r8(B,C)"}};
		String[][] x42 = {{"fetch","write_r8_r8(B,D)"}};
		String[][] x43 = {{"fetch","write_r8_r8(B,E)"}};
		String[][] x44 = {{"fetch","write_r8_r8(B,H)"}};
		String[][] x45 = {{"fetch","write_r8_r8(B,L)"}};
		String[][] x46 = {{"write_r8_r8(B,(HL))"},{"fetch"}};
		String[][] x47 = {{"fetch","write_r8_r8(B,A)"}};
		String[][] x48 = {{"fetch","write_r8_r8(C,B)"}};
		String[][] x49 = {{"fetch","write_r8_r8(C,C)"}};
		String[][] x4A = {{"fetch","write_r8_r8(C,D)"}};
		String[][] x4B = {{"fetch","write_r8_r8(C,E)"}};
		String[][] x4C = {{"fetch","write_r8_r8(C,H)"}};
		String[][] x4D = {{"fetch","write_r8_r8(C,L)"}};
		String[][] x4E = {{"write_r8_r8(C,(HL))"},{"fetch"}};
		String[][] x4F = {{"fetch","write_r8_r8(C,A)"}};
		String[][] x50 = {{"fetch","write_r8_r8(D,B)"}};
		String[][] x51 = {{"fetch","write_r8_r8(D,C)"}};
		String[][] x52 = {{"fetch","write_r8_r8(D,D)"}};
		String[][] x53 = {{"fetch","write_r8_r8(D,E)"}};
		String[][] x54 = {{"fetch","write_r8_r8(D,H)"}};
		String[][] x55 = {{"fetch","write_r8_r8(D,L)"}};
		String[][] x56 = {{"write_r8_r8(D,(HL))"},{"fetch"}};
		String[][] x57 = {{"fetch","write_r8_r8(D,A)"}};
		String[][] x58 = {{"fetch","write_r8_r8(E,B)"}};
		String[][] x59 = {{"fetch","write_r8_r8(E,C)"}};
		String[][] x5A = {{"fetch","write_r8_r8(E,D)"}};
		String[][] x5B = {{"fetch","write_r8_r8(E,E)"}};
		String[][] x5C = {{"fetch","write_r8_r8(E,H)"}};
		String[][] x5D = {{"fetch","write_r8_r8(E,L)"}};
		String[][] x5E = {{"write_r8_r8(E,(HL))"},{"fetch"}};
		String[][] x5F = {{"fetch","write_r8_r8(E,A)"}};
		String[][] x60 = {{"fetch","write_r8_r8(H,B)"}};
		String[][] x61 = {{"fetch","write_r8_r8(H,C)"}};
		String[][] x62 = {{"fetch","write_r8_r8(H,D)"}};
		String[][] x63 = {{"fetch","write_r8_r8(H,E)"}};
		String[][] x64 = {{"fetch","write_r8_r8(H,H)"}};
		String[][] x65 = {{"fetch","write_r8_r8(H,L)"}};
		String[][] x66 = {{"write_r8_r8(H,(HL))"},{"fetch"}};
		String[][] x67 = {{"fetch","write_r8_r8(H,A)"}};
		String[][] x68 = {{"fetch","write_r8_r8(L,B)"}};
		String[][] x69 = {{"fetch","write_r8_r8(L,C)"}};
		String[][] x6A = {{"fetch","write_r8_r8(L,D)"}};
		String[][] x6B = {{"fetch","write_r8_r8(L,E)"}};
		String[][] x6C = {{"fetch","write_r8_r8(L,H)"}};
		String[][] x6D = {{"fetch","write_r8_r8(L,L)"}};
		String[][] x6E = {{"write_r8_r8(L,(HL))"},{"fetch"}};
		String[][] x6F = {{"fetch","write_r8_r8(L,A)"}};
		String[][] x70 = {{"write_r8_r8((HL),B)"},{"fetch"}};
		String[][] x71 = {{"write_r8_r8((HL),C)"},{"fetch"}};
		String[][] x72 = {{"write_r8_r8((HL),D)"},{"fetch"}};
		String[][] x73 = {{"write_r8_r8((HL),E)"},{"fetch"}};
		String[][] x74 = {{"write_r8_r8((HL),H)"},{"fetch"}};
		String[][] x75 = {{"write_r8_r8((HL),L)"},{"fetch"}};
		String[][] x76 = {{"HALT"}};
		String[][] x77 = {{"write_r8_r8((HL),A)"},{"fetch"}};
		String[][] x78 = {{"fetch","write_r8_r8(A,B)"}};
		String[][] x79 = {{"fetch","write_r8_r8(A,C)"}};
		String[][] x7A = {{"fetch","write_r8_r8(A,D)"}};
		String[][] x7B = {{"fetch","write_r8_r8(A,E)"}};
		String[][] x7C = {{"fetch","write_r8_r8(A,H)"}};
		String[][] x7D = {{"fetch","write_r8_r8(A,L)"}};
		String[][] x7E = {{"write_r8_r8(A,(HL))"},{"fetch"}};
		String[][] x7F = {{"fetch","write_r8_r8(A,A)"}};
		String[][] x80 = {{"ADD_r8(B)","fetch"}};
		String[][] x81 = {{"ADD_r8(C)","fetch"}};
		String[][] x82 = {{"ADD_r8(D)","fetch"}};
		String[][] x83 = {{"ADD_r8(E)","fetch"}};
		String[][] x84 = {{"ADD_r8(H)","fetch"}};
		String[][] x85 = {{"ADD_r8(L)","fetch"}};
		String[][] x86 = {{"ADD_r8((HL))"},{"fetch"}};
		String[][] x87 = {{"ADD_r8(A)","fetch"}};
		String[][] x88 = {{"ADC_r8(B)","fetch"}};
		String[][] x89 = {{"ADC_r8(C)","fetch"}};
		String[][] x8A = {{"ADC_r8(D)","fetch"}};
		String[][] x8B = {{"ADC_r8(E)","fetch"}};
		String[][] x8C = {{"ADC_r8(H)","fetch"}};
		String[][] x8D = {{"ADC_r8(L)","fetch"}};
		String[][] x8E = {{"ADC_r8((HL))"},{"fetch"}};
		String[][] x8F = {{"ADC_r8(A)","fetch"}};
		String[][] x90 = {{"SUB_r8(B)","fetch"}};
		String[][] x91 = {{"SUB_r8(C)","fetch"}};
		String[][] x92 = {{"SUB_r8(D)","fetch"}};
		String[][] x93 = {{"SUB_r8(E)","fetch"}};
		String[][] x94 = {{"SUB_r8(H)","fetch"}};
		String[][] x95 = {{"SUB_r8(L)","fetch"}};
		String[][] x96 = {{"SUB_r8((HL))"},{"fetch"}};
		String[][] x97 = {{"SUB_r8(A)","fetch"}};
		String[][] x98 = {{"SBC_r8(B)","fetch"}};
		String[][] x99 = {{"SBC_r8(C)","fetch"}};
		String[][] x9A = {{"SBC_r8(D)","fetch"}};
		String[][] x9B = {{"SBC_r8(E)","fetch"}};
		String[][] x9C = {{"SBC_r8(H)","fetch"}};
		String[][] x9D = {{"SBC_r8(L)","fetch"}};
		String[][] x9E = {{"SBC_r8((HL))"},{"fetch"}};
		String[][] x9F = {{"SBC_r8(A)","fetch"}};
		String[][] xA0 = {{"AND_r8(B)","fetch"}};
		String[][] xA1 = {{"AND_r8(C)","fetch"}};
		String[][] xA2 = {{"AND_r8(D)","fetch"}};
		String[][] xA3 = {{"AND_r8(E)","fetch"}};
		String[][] xA4 = {{"AND_r8(H)","fetch"}};
		String[][] xA5 = {{"AND_r8(L)","fetch"}};
		String[][] xA6 = {{"AND_r8((HL))"},{"fetch"}};
		String[][] xA7 = {{"AND_r8(A)","fetch"}};
		String[][] xA8 = {{"XOR_r8(B)","fetch"}};
		String[][] xA9 = {{"XOR_r8(C)","fetch"}};
		String[][] xAA = {{"XOR_r8(D)","fetch"}};
		String[][] xAB = {{"XOR_r8(E)","fetch"}};
		String[][] xAC = {{"XOR_r8(H)","fetch"}};
		String[][] xAD = {{"XOR_r8(L)","fetch"}};
		String[][] xAE = {{"XOR_r8((HL))"},{"fetch"}};
		String[][] xAF = {{"XOR_r8(A)","fetch"}};
		String[][] xB0 = {{"ORA_r8(B)","fetch"}};
		String[][] xB1 = {{"ORA_r8(C)","fetch"}};
		String[][] xB2 = {{"ORA_r8(D)","fetch"}};
		String[][] xB3 = {{"ORA_r8(E)","fetch"}};
		String[][] xB4 = {{"ORA_r8(H)","fetch"}};
		String[][] xB5 = {{"ORA_r8(L)","fetch"}};
		String[][] xB6 = {{"ORA_r8((HL))"},{"fetch"}};
		String[][] xB7 = {{"ORA_r8(A)","fetch"}};
		String[][] xB8 = {{"CP_r8(B)","fetch"}};
		String[][] xB9 = {{"CP_r8(C)","fetch"}};
		String[][] xBA = {{"CP_r8(D)","fetch"}};
		String[][] xBB = {{"CP_r8(E)","fetch"}};
		String[][] xBC = {{"CP_r8(H)","fetch"}};
		String[][] xBD = {{"CP_r8(L)","fetch"}};
		String[][] xBE = {{"CP_r8((HL))"},{"fetch"}};
		String[][] xBF = {{"CP_r8(A)","fetch"}};
		String[][] xC0 = {{"checkCondition(NZ)"},{"read_LSB_r16(SP)","increment_r16(SP)"},{"read_MSB_r16(SP)","increment_r16(SP)"},{"write_r16_n16(PC)"},{"fetch"}};
		String[][] xC1 = {{"write_LSB((SP))","increment_r16(SP)"},{"write_MSB((SP))","increment_r16(SP)"},{"fetch","write_r16_n16(BC)"}};
		String[][] xC2 = {{"read_lsb"},{"read_msb","checkCondition(NZ)"},{"write_PC_a16"},{"fetch"}};
		String[][] xC3 = {{"read_lsb"},{"read_msb"},{"write_PC_a16"},{"fetch"}};
		String[][] xC4 = {{"read_lsb"},{"read_msb","checkCondition(NZ)"},{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC_a16"},{"fetch"}};
		String[][] xC5 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(BC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(BC)"},{"fetch"}};
		String[][] xC6 = {{"read_lsb"},{"ADD_n8","fetch"}};
		String[][] xC7 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(00)"},{"fetch"}};
		String[][] xC8 = {{"checkCondition(Z)"},{"read_LSB_r16(SP)","increment_r16(SP)"},{"read_MSB_r16(SP)","increment_r16(SP)"},{"write_r16_n16(PC)"},{"fetch"}};
		String[][] xC9 = {{"read_LSB_r16(SP)","increment_r16(SP)"},{"read_MSB_r16(SP)","increment_r16(SP)"},{"write_r16_n16(PC)"},{"fetch"}};
		String[][] xCA = {{"read_lsb"},{"read_msb","checkCondition(Z)"},{"write_PC_a16"},{"fetch"}};
		String[][] xCC = {{"read_lsb"},{"read_msb","checkCondition(Z)"},{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC_a16"},{"fetch"}};
		String[][] xCD = {{"read_lsb"},{"read_msb"},{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC_a16"},{"fetch"}};
		String[][] xCE = {{"read_lsb"},{"ADC_n8","fetch"}};
		String[][] xCF = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(08)"},{"fetch"}};
		String[][] xD0 = {{"checkCondition(NC)"},{"read_LSB_r16(SP)","increment_r16(SP)"},{"read_MSB_r16(SP)","increment_r16(SP)"},{"write_r16_n16(PC)"},{"fetch"}};
		String[][] xD1 = {{"write_LSB((SP))","increment_r16(SP)"},{"write_MSB((SP))","increment_r16(SP)"},{"fetch","write_r16_n16(DE)"}};
		String[][] xD2 = {{"read_lsb"},{"read_msb","checkCondition(NC)"},{"write_PC_a16"},{"fetch"}};
		String[][] xD4 = {{"read_lsb"},{"read_msb","checkCondition(NC)"},{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC_a16"},{"fetch"}};
		String[][] xD5 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(DE)","decrement_r16(SP)"},{"write_Stack_r16_LSB(DE)"},{"fetch"}};
		String[][] xD6 = {{"read_lsb"},{"SUB_n8","fetch"}};
		String[][] xD7 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(10)"},{"fetch"}};
		String[][] xD8 = {{"checkCondition(C)"},{"read_LSB_r16(SP)","increment_r16(SP)"},{"read_MSB_r16(SP)","increment_r16(SP)"},{"write_r16_n16(PC)"},{"fetch"}};
		String[][] xD9 = {{"write_LSB((SP))","increment_r16(SP)"},{"write_MSB((SP))","increment_r16(SP)"},{"write_r16_n16(PC)"},{"EI","fetch"}};
		String[][] xDA = {{"read_lsb"},{"read_msb","checkCondition(C)"},{"write_PC_a16"},{"fetch"}};
		String[][] xDC = {{"read_lsb"},{"read_msb","checkCondition(C)"},{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC_a16"},{"fetch"}};
		String[][] xDE = {{"read_lsb"},{"SBC_n8","fetch"}};
		String[][] xDF = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(18)"},{"fetch"}};
		String[][] xE0 = {{"read_lsb"},{"write_high_r8(A)"},{"fetch"}};
		String[][] xE1 = {{"write_LSB((SP))","increment_r16(SP)"},{"write_MSB((SP))","increment_r16(SP)"},{"fetch","write_r16_n16(HL)"}};
		String[][] xE2 = {{"write_LSB(C)","write_high_r8(A)"},{"fetch"}};
		String[][] xE5 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(HL)","decrement_r16(SP)"},{"write_Stack_r16_LSB(HL)"},{"fetch"}};
		String[][] xE6 = {{"read_lsb"},{"AND_n8","fetch"}};
		String[][] xE7 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(20)"},{"fetch"}};
		String[][] xE8 = {{"read_lsb"},{"no_op"},{"ADD_SP_e8"},{"fetch"}};
		String[][] xE9 = {{"JP_HL","fetch"}};
		String[][] xEA = {{"read_lsb"},{"read_msb"},{"write_a16_r8(A)"},{"fetch"}};
		String[][] xEE = {{"read_lsb"},{"XOR_n8","fetch"}};
		String[][] xEF = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(28)"},{"fetch"}};
		String[][] xF0 = {{"read_lsb"},{"read_high_r8(A)"},{"fetch"}};
		String[][] xF1 = {{"write_LSB((SP))","increment_r16(SP)"},{"write_MSB((SP))","increment_r16(SP)"},{"fetch","write_r16_n16(AF)"}};
		String[][] xF2 = {{"write_LSB(C)","read_high_r8(A)"},{"fetch"}};
		String[][] xF3 = {{"DI","fetch"}};
		String[][] xF5 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(AF)","decrement_r16(SP)"},{"write_Stack_r16_LSB(AF)"},{"fetch"}};
		String[][] xF6 = {{"read_lsb"},{"ORA_n8","fetch"}};
		String[][] xF7 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(30)"},{"fetch"}};
		String[][] xF8 = {{"read_lsb"},{"LD_HL_SP_e8"},{"fetch"}};
		String[][] xF9 = {{"write_r16_r16(SP,HL)"},{"fetch"}};
		String[][] xFA = {{"read_lsb"},{"read_msb"},{"write_r8_abs_n16(A)"},{"fetch"}};
		String[][] xFB = {{"fetch","EI"}};
		String[][] xFE = {{"read_lsb"},{"CP_n8","fetch"}};
		String[][] xFF = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)","write_PC(38)"},{"fetch"}};
		String[][] xDE00 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)"},{"write_PC(40)"},{"fetch"}};
		String[][] xDE01 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)"},{"write_PC(48)"},{"fetch"}};
		String[][] xDE02 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)"},{"write_PC(50)"},{"fetch"}};
		String[][] xDE03 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)"},{"write_PC(58)"},{"fetch"}};
		String[][] xDE04 = {{"decrement_r16(SP)"},{"write_Stack_r16_MSB(PC)","decrement_r16(SP)"},{"write_Stack_r16_LSB(PC)"},{"write_PC(60)"},{"fetch"}};
		String[][] xCB00 = {{"RLC_r8(B)"},{"fetch"}};
		String[][] xCB01 = {{"RLC_r8(C)"},{"fetch"}};
		String[][] xCB02 = {{"RLC_r8(D)"},{"fetch"}};
		String[][] xCB03 = {{"RLC_r8(E)"},{"fetch"}};
		String[][] xCB04 = {{"RLC_r8(H)"},{"fetch"}};
		String[][] xCB05 = {{"RLC_r8(L)"},{"fetch"}};
		String[][] xCB06 = {{"no_op"},{"save_r8((HL))"},{"RLC_r8(saved)"},{"fetch"}};
		String[][] xCB07 = {{"RLC_r8(A)"},{"fetch"}};
		String[][] xCB08 = {{"RRC_r8(B)"},{"fetch"}};
		String[][] xCB09 = {{"RRC_r8(C)"},{"fetch"}};
		String[][] xCB0A = {{"RRC_r8(D)"},{"fetch"}};
		String[][] xCB0B = {{"RRC_r8(E)"},{"fetch"}};
		String[][] xCB0C = {{"RRC_r8(H)"},{"fetch"}};
		String[][] xCB0D = {{"RRC_r8(L)"},{"fetch"}};
		String[][] xCB0E = {{"no_op"},{"save_r8((HL))"},{"RRC_r8(saved)"},{"fetch"}};
		String[][] xCB0F = {{"RRC_r8(A)"},{"fetch"}};
		String[][] xCB10 = {{"RL_r8(B)"},{"fetch"}};
		String[][] xCB11 = {{"RL_r8(C)"},{"fetch"}};
		String[][] xCB12 = {{"RL_r8(D)"},{"fetch"}};
		String[][] xCB13 = {{"RL_r8(E)"},{"fetch"}};
		String[][] xCB14 = {{"RL_r8(H)"},{"fetch"}};
		String[][] xCB15 = {{"RL_r8(L)"},{"fetch"}};
		String[][] xCB16 = {{"no_op"},{"save_r8((HL))"},{"RL_r8(saved)"},{"fetch"}};
		String[][] xCB17 = {{"RL_r8(A)"},{"fetch"}};
		String[][] xCB18 = {{"RR_r8(B)"},{"fetch"}};
		String[][] xCB19 = {{"RR_r8(C)"},{"fetch"}};
		String[][] xCB1A = {{"RR_r8(D)"},{"fetch"}};
		String[][] xCB1B = {{"RR_r8(E)"},{"fetch"}};
		String[][] xCB1C = {{"RR_r8(H)"},{"fetch"}};
		String[][] xCB1D = {{"RR_r8(L)"},{"fetch"}};
		String[][] xCB1E = {{"no_op"},{"save_r8((HL))"},{"RR_r8(saved)"},{"fetch"}};
		String[][] xCB1F = {{"RR_r8(A)"},{"fetch"}};
		String[][] xCB20 = {{"SLA_r8(B)"},{"fetch"}};
		String[][] xCB21 = {{"SLA_r8(C)"},{"fetch"}};
		String[][] xCB22 = {{"SLA_r8(D)"},{"fetch"}};
		String[][] xCB23 = {{"SLA_r8(E)"},{"fetch"}};
		String[][] xCB24 = {{"SLA_r8(H)"},{"fetch"}};
		String[][] xCB25 = {{"SLA_r8(L)"},{"fetch"}};
		String[][] xCB26 = {{"no_op"},{"save_r8((HL))"},{"SLA_r8(saved)"},{"fetch"}};
		String[][] xCB27 = {{"SLA_r8(A)"},{"fetch"}};
		String[][] xCB28 = {{"SRA_r8(B)"},{"fetch"}};
		String[][] xCB29 = {{"SRA_r8(C)"},{"fetch"}};
		String[][] xCB2A = {{"SRA_r8(D)"},{"fetch"}};
		String[][] xCB2B = {{"SRA_r8(E)"},{"fetch"}};
		String[][] xCB2C = {{"SRA_r8(H)"},{"fetch"}};
		String[][] xCB2D = {{"SRA_r8(L)"},{"fetch"}};
		String[][] xCB2E = {{"no_op"},{"save_r8((HL))"},{"SRA_r8(saved)"},{"fetch"}};
		String[][] xCB2F = {{"SRA_r8(A)"},{"fetch"}};
		String[][] xCB30 = {{"SWAP(B)"},{"fetch"}};
		String[][] xCB31 = {{"SWAP(C)"},{"fetch"}};
		String[][] xCB32 = {{"SWAP(D)"},{"fetch"}};
		String[][] xCB33 = {{"SWAP(E)"},{"fetch"}};
		String[][] xCB34 = {{"SWAP(H)"},{"fetch"}};
		String[][] xCB35 = {{"SWAP(L)"},{"fetch"}};
		String[][] xCB36 = {{"no_op"},{"save_r8((HL))"},{"SWAP(saved)"},{"fetch"}};
		String[][] xCB37 = {{"SWAP(A)"},{"fetch"}};
		String[][] xCB38 = {{"SRL_r8(B)"},{"fetch"}};
		String[][] xCB39 = {{"SRL_r8(C)"},{"fetch"}};
		String[][] xCB3A = {{"SRL_r8(D)"},{"fetch"}};
		String[][] xCB3B = {{"SRL_r8(E)"},{"fetch"}};
		String[][] xCB3C = {{"SRL_r8(H)"},{"fetch"}};
		String[][] xCB3D = {{"SRL_r8(L)"},{"fetch"}};
		String[][] xCB3E = {{"no_op"},{"save_r8((HL))"},{"SRL_r8(saved)"},{"fetch"}};
		String[][] xCB3F = {{"SRL_r8(A)"},{"fetch"}};
		String[][] xCB40 = {{"BIT_b_r8(0,B)"},{"fetch"}};
		String[][] xCB41 = {{"BIT_b_r8(0,C)"},{"fetch"}};
		String[][] xCB42 = {{"BIT_b_r8(0,D)"},{"fetch"}};
		String[][] xCB43 = {{"BIT_b_r8(0,E)"},{"fetch"}};
		String[][] xCB44 = {{"BIT_b_r8(0,H)"},{"fetch"}};
		String[][] xCB45 = {{"BIT_b_r8(0,L)"},{"fetch"}};
		String[][] xCB46 = {{"no_op"},{"BIT_b_r8(0,(HL))"},{"fetch"}};
		String[][] xCB47 = {{"BIT_b_r8(0,A)"},{"fetch"}};
		String[][] xCB48 = {{"BIT_b_r8(1,B)"},{"fetch"}};
		String[][] xCB49 = {{"BIT_b_r8(1,C)"},{"fetch"}};
		String[][] xCB4A = {{"BIT_b_r8(1,D)"},{"fetch"}};
		String[][] xCB4B = {{"BIT_b_r8(1,E)"},{"fetch"}};
		String[][] xCB4C = {{"BIT_b_r8(1,H)"},{"fetch"}};
		String[][] xCB4D = {{"BIT_b_r8(1,L)"},{"fetch"}};
		String[][] xCB4E = {{"no_op"},{"BIT_b_r8(1,(HL))"},{"fetch"}};
		String[][] xCB4F = {{"BIT_b_r8(1,A)"},{"fetch"}};
		String[][] xCB50 = {{"BIT_b_r8(2,B)"},{"fetch"}};
		String[][] xCB51 = {{"BIT_b_r8(2,C)"},{"fetch"}};
		String[][] xCB52 = {{"BIT_b_r8(2,D)"},{"fetch"}};
		String[][] xCB53 = {{"BIT_b_r8(2,E)"},{"fetch"}};
		String[][] xCB54 = {{"BIT_b_r8(2,H)"},{"fetch"}};
		String[][] xCB55 = {{"BIT_b_r8(2,L)"},{"fetch"}};
		String[][] xCB56 = {{"no_op"},{"BIT_b_r8(2,(HL))"},{"fetch"}};
		String[][] xCB57 = {{"BIT_b_r8(2,A)"},{"fetch"}};
		String[][] xCB58 = {{"BIT_b_r8(3,B)"},{"fetch"}};
		String[][] xCB59 = {{"BIT_b_r8(3,C)"},{"fetch"}};
		String[][] xCB5A = {{"BIT_b_r8(3,D)"},{"fetch"}};
		String[][] xCB5B = {{"BIT_b_r8(3,E)"},{"fetch"}};
		String[][] xCB5C = {{"BIT_b_r8(3,H)"},{"fetch"}};
		String[][] xCB5D = {{"BIT_b_r8(3,L)"},{"fetch"}};
		String[][] xCB5E = {{"no_op"},{"BIT_b_r8(3,(HL))"},{"fetch"}};
		String[][] xCB5F = {{"BIT_b_r8(3,A)"},{"fetch"}};
		String[][] xCB60 = {{"BIT_b_r8(4,B)"},{"fetch"}};
		String[][] xCB61 = {{"BIT_b_r8(4,C)"},{"fetch"}};
		String[][] xCB62 = {{"BIT_b_r8(4,D)"},{"fetch"}};
		String[][] xCB63 = {{"BIT_b_r8(4,E)"},{"fetch"}};
		String[][] xCB64 = {{"BIT_b_r8(4,H)"},{"fetch"}};
		String[][] xCB65 = {{"BIT_b_r8(4,L)"},{"fetch"}};
		String[][] xCB66 = {{"no_op"},{"BIT_b_r8(4,(HL))"},{"fetch"}};
		String[][] xCB67 = {{"BIT_b_r8(4,A)"},{"fetch"}};
		String[][] xCB68 = {{"BIT_b_r8(5,B)"},{"fetch"}};
		String[][] xCB69 = {{"BIT_b_r8(5,C)"},{"fetch"}};
		String[][] xCB6A = {{"BIT_b_r8(5,D)"},{"fetch"}};
		String[][] xCB6B = {{"BIT_b_r8(5,E)"},{"fetch"}};
		String[][] xCB6C = {{"BIT_b_r8(5,H)"},{"fetch"}};
		String[][] xCB6D = {{"BIT_b_r8(5,L)"},{"fetch"}};
		String[][] xCB6E = {{"no_op"},{"BIT_b_r8(5,(HL))"},{"fetch"}};
		String[][] xCB6F = {{"BIT_b_r8(5,A)"},{"fetch"}};
		String[][] xCB70 = {{"BIT_b_r8(6,B)"},{"fetch"}};
		String[][] xCB71 = {{"BIT_b_r8(6,C)"},{"fetch"}};
		String[][] xCB72 = {{"BIT_b_r8(6,D)"},{"fetch"}};
		String[][] xCB73 = {{"BIT_b_r8(6,E)"},{"fetch"}};
		String[][] xCB74 = {{"BIT_b_r8(6,H)"},{"fetch"}};
		String[][] xCB75 = {{"BIT_b_r8(6,L)"},{"fetch"}};
		String[][] xCB76 = {{"no_op"},{"BIT_b_r8(6,(HL))"},{"fetch"}};
		String[][] xCB77 = {{"BIT_b_r8(6,A)"},{"fetch"}};
		String[][] xCB78 = {{"BIT_b_r8(7,B)"},{"fetch"}};
		String[][] xCB79 = {{"BIT_b_r8(7,C)"},{"fetch"}};
		String[][] xCB7A = {{"BIT_b_r8(7,D)"},{"fetch"}};
		String[][] xCB7B = {{"BIT_b_r8(7,E)"},{"fetch"}};
		String[][] xCB7C = {{"BIT_b_r8(7,H)"},{"fetch"}};
		String[][] xCB7D = {{"BIT_b_r8(7,L)"},{"fetch"}};
		String[][] xCB7E = {{"no_op"},{"BIT_b_r8(7,(HL))"},{"fetch"}};
		String[][] xCB7F = {{"BIT_b_r8(7,A)"},{"fetch"}};
		String[][] xCB80 = {{"RES_b_r8(0,B)"},{"fetch"}};
		String[][] xCB81 = {{"RES_b_r8(0,C)"},{"fetch"}};
		String[][] xCB82 = {{"RES_b_r8(0,D)"},{"fetch"}};
		String[][] xCB83 = {{"RES_b_r8(0,E)"},{"fetch"}};
		String[][] xCB84 = {{"RES_b_r8(0,H)"},{"fetch"}};
		String[][] xCB85 = {{"RES_b_r8(0,L)"},{"fetch"}};
		String[][] xCB86 = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(0,saved)"},{"fetch"}};
		String[][] xCB87 = {{"RES_b_r8(0,A)"},{"fetch"}};
		String[][] xCB88 = {{"RES_b_r8(1,B)"},{"fetch"}};
		String[][] xCB89 = {{"RES_b_r8(1,C)"},{"fetch"}};
		String[][] xCB8A = {{"RES_b_r8(1,D)"},{"fetch"}};
		String[][] xCB8B = {{"RES_b_r8(1,E)"},{"fetch"}};
		String[][] xCB8C = {{"RES_b_r8(1,H)"},{"fetch"}};
		String[][] xCB8D = {{"RES_b_r8(1,L)"},{"fetch"}};
		String[][] xCB8E = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(1,saved)"},{"fetch"}};
		String[][] xCB8F = {{"RES_b_r8(1,A)"},{"fetch"}};
		String[][] xCB90 = {{"RES_b_r8(2,B)"},{"fetch"}};
		String[][] xCB91 = {{"RES_b_r8(2,C)"},{"fetch"}};
		String[][] xCB92 = {{"RES_b_r8(2,D)"},{"fetch"}};
		String[][] xCB93 = {{"RES_b_r8(2,E)"},{"fetch"}};
		String[][] xCB94 = {{"RES_b_r8(2,H)"},{"fetch"}};
		String[][] xCB95 = {{"RES_b_r8(2,L)"},{"fetch"}};
		String[][] xCB96 = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(2,saved)"},{"fetch"}};
		String[][] xCB97 = {{"RES_b_r8(2,A)"},{"fetch"}};
		String[][] xCB98 = {{"RES_b_r8(3,B)"},{"fetch"}};
		String[][] xCB99 = {{"RES_b_r8(3,C)"},{"fetch"}};
		String[][] xCB9A = {{"RES_b_r8(3,D)"},{"fetch"}};
		String[][] xCB9B = {{"RES_b_r8(3,E)"},{"fetch"}};
		String[][] xCB9C = {{"RES_b_r8(3,H)"},{"fetch"}};
		String[][] xCB9D = {{"RES_b_r8(3,L)"},{"fetch"}};
		String[][] xCB9E = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(3,saved)"},{"fetch"}};
		String[][] xCB9F = {{"RES_b_r8(3,A)"},{"fetch"}};
		String[][] xCBA0 = {{"RES_b_r8(4,B)"},{"fetch"}};
		String[][] xCBA1 = {{"RES_b_r8(4,C)"},{"fetch"}};
		String[][] xCBA2 = {{"RES_b_r8(4,D)"},{"fetch"}};
		String[][] xCBA3 = {{"RES_b_r8(4,E)"},{"fetch"}};
		String[][] xCBA4 = {{"RES_b_r8(4,H)"},{"fetch"}};
		String[][] xCBA5 = {{"RES_b_r8(4,L)"},{"fetch"}};
		String[][] xCBA6 = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(4,saved)"},{"fetch"}};
		String[][] xCBA7 = {{"RES_b_r8(4,A)"},{"fetch"}};
		String[][] xCBA8 = {{"RES_b_r8(5,B)"},{"fetch"}};
		String[][] xCBA9 = {{"RES_b_r8(5,C)"},{"fetch"}};
		String[][] xCBAA = {{"RES_b_r8(5,D)"},{"fetch"}};
		String[][] xCBAB = {{"RES_b_r8(5,E)"},{"fetch"}};
		String[][] xCBAC = {{"RES_b_r8(5,H)"},{"fetch"}};
		String[][] xCBAD = {{"RES_b_r8(5,L)"},{"fetch"}};
		String[][] xCBAE = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(5,saved)"},{"fetch"}};
		String[][] xCBAF = {{"RES_b_r8(5,A)"},{"fetch"}};
		String[][] xCBB0 = {{"RES_b_r8(6,B)"},{"fetch"}};
		String[][] xCBB1 = {{"RES_b_r8(6,C)"},{"fetch"}};
		String[][] xCBB2 = {{"RES_b_r8(6,D)"},{"fetch"}};
		String[][] xCBB3 = {{"RES_b_r8(6,E)"},{"fetch"}};
		String[][] xCBB4 = {{"RES_b_r8(6,H)"},{"fetch"}};
		String[][] xCBB5 = {{"RES_b_r8(6,L)"},{"fetch"}};
		String[][] xCBB6 = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(6,saved)"},{"fetch"}};
		String[][] xCBB7 = {{"RES_b_r8(6,A)"},{"fetch"}};
		String[][] xCBB8 = {{"RES_b_r8(7,B)"},{"fetch"}};
		String[][] xCBB9 = {{"RES_b_r8(7,C)"},{"fetch"}};
		String[][] xCBBA = {{"RES_b_r8(7,D)"},{"fetch"}};
		String[][] xCBBB = {{"RES_b_r8(7,E)"},{"fetch"}};
		String[][] xCBBC = {{"RES_b_r8(7,H)"},{"fetch"}};
		String[][] xCBBD = {{"RES_b_r8(7,L)"},{"fetch"}};
		String[][] xCBBE = {{"no_op"},{"save_r8((HL))"},{"RES_b_r8(7,saved)"},{"fetch"}};
		String[][] xCBBF = {{"RES_b_r8(7,A)"},{"fetch"}};
		String[][] xCBC0 = {{"SET_b_r8(0,B)"},{"fetch"}};
		String[][] xCBC1 = {{"SET_b_r8(0,C)"},{"fetch"}};
		String[][] xCBC2 = {{"SET_b_r8(0,D)"},{"fetch"}};
		String[][] xCBC3 = {{"SET_b_r8(0,E)"},{"fetch"}};
		String[][] xCBC4 = {{"SET_b_r8(0,H)"},{"fetch"}};
		String[][] xCBC5 = {{"SET_b_r8(0,L)"},{"fetch"}};
		String[][] xCBC6 = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(0,saved)"},{"fetch"}};
		String[][] xCBC7 = {{"SET_b_r8(0,A)"},{"fetch"}};
		String[][] xCBC8 = {{"SET_b_r8(1,B)"},{"fetch"}};
		String[][] xCBC9 = {{"SET_b_r8(1,C)"},{"fetch"}};
		String[][] xCBCA = {{"SET_b_r8(1,D)"},{"fetch"}};
		String[][] xCBCB = {{"SET_b_r8(1,E)"},{"fetch"}};
		String[][] xCBCC = {{"SET_b_r8(1,H)"},{"fetch"}};
		String[][] xCBCD = {{"SET_b_r8(1,L)"},{"fetch"}};
		String[][] xCBCE = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(1,saved)"},{"fetch"}};
		String[][] xCBCF = {{"SET_b_r8(1,A)"},{"fetch"}};
		String[][] xCBD0 = {{"SET_b_r8(2,B)"},{"fetch"}};
		String[][] xCBD1 = {{"SET_b_r8(2,C)"},{"fetch"}};
		String[][] xCBD2 = {{"SET_b_r8(2,D)"},{"fetch"}};
		String[][] xCBD3 = {{"SET_b_r8(2,E)"},{"fetch"}};
		String[][] xCBD4 = {{"SET_b_r8(2,H)"},{"fetch"}};
		String[][] xCBD5 = {{"SET_b_r8(2,L)"},{"fetch"}};
		String[][] xCBD6 = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(2,saved)"},{"fetch"}};
		String[][] xCBD7 = {{"SET_b_r8(2,A)"},{"fetch"}};
		String[][] xCBD8 = {{"SET_b_r8(3,B)"},{"fetch"}};
		String[][] xCBD9 = {{"SET_b_r8(3,C)"},{"fetch"}};
		String[][] xCBDA = {{"SET_b_r8(3,D)"},{"fetch"}};
		String[][] xCBDB = {{"SET_b_r8(3,E)"},{"fetch"}};
		String[][] xCBDC = {{"SET_b_r8(3,H)"},{"fetch"}};
		String[][] xCBDD = {{"SET_b_r8(3,L)"},{"fetch"}};
		String[][] xCBDE = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(3,saved)"},{"fetch"}};
		String[][] xCBDF = {{"SET_b_r8(3,A)"},{"fetch"}};
		String[][] xCBE0 = {{"SET_b_r8(4,B)"},{"fetch"}};
		String[][] xCBE1 = {{"SET_b_r8(4,C)"},{"fetch"}};
		String[][] xCBE2 = {{"SET_b_r8(4,D)"},{"fetch"}};
		String[][] xCBE3 = {{"SET_b_r8(4,E)"},{"fetch"}};
		String[][] xCBE4 = {{"SET_b_r8(4,H)"},{"fetch"}};
		String[][] xCBE5 = {{"SET_b_r8(4,L)"},{"fetch"}};
		String[][] xCBE6 = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(4,saved)"},{"fetch"}};
		String[][] xCBE7 = {{"SET_b_r8(4,A)"},{"fetch"}};
		String[][] xCBE8 = {{"SET_b_r8(5,B)"},{"fetch"}};
		String[][] xCBE9 = {{"SET_b_r8(5,C)"},{"fetch"}};
		String[][] xCBEA = {{"SET_b_r8(5,D)"},{"fetch"}};
		String[][] xCBEB = {{"SET_b_r8(5,E)"},{"fetch"}};
		String[][] xCBEC = {{"SET_b_r8(5,H)"},{"fetch"}};
		String[][] xCBED = {{"SET_b_r8(5,L)"},{"fetch"}};
		String[][] xCBEE = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(5,saved)"},{"fetch"}};
		String[][] xCBEF = {{"SET_b_r8(5,A)"},{"fetch"}};
		String[][] xCBF0 = {{"SET_b_r8(6,B)"},{"fetch"}};
		String[][] xCBF1 = {{"SET_b_r8(6,C)"},{"fetch"}};
		String[][] xCBF2 = {{"SET_b_r8(6,D)"},{"fetch"}};
		String[][] xCBF3 = {{"SET_b_r8(6,E)"},{"fetch"}};
		String[][] xCBF4 = {{"SET_b_r8(6,H)"},{"fetch"}};
		String[][] xCBF5 = {{"SET_b_r8(6,L)"},{"fetch"}};
		String[][] xCBF6 = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(6,saved)"},{"fetch"}};
		String[][] xCBF7 = {{"SET_b_r8(6,A)"},{"fetch"}};
		String[][] xCBF8 = {{"SET_b_r8(7,B)"},{"fetch"}};
		String[][] xCBF9 = {{"SET_b_r8(7,C)"},{"fetch"}};
		String[][] xCBFA = {{"SET_b_r8(7,D)"},{"fetch"}};
		String[][] xCBFB = {{"SET_b_r8(7,E)"},{"fetch"}};
		String[][] xCBFC = {{"SET_b_r8(7,H)"},{"fetch"}};
		String[][] xCBFD = {{"SET_b_r8(7,L)"},{"fetch"}};
		String[][] xCBFE = {{"no_op"},{"save_r8((HL))"},{"SET_b_r8(7,saved)"},{"fetch"}};
		String[][] xCBFF = {{"SET_b_r8(7,A)"},{"fetch"}};

		opcodeToInstruction.put(0x00,x00);
		opcodeToInstruction.put(0x01,x01);
		opcodeToInstruction.put(0x02,x02);
		opcodeToInstruction.put(0x03,x03);
		opcodeToInstruction.put(0x04,x04);
		opcodeToInstruction.put(0x05,x05);
		opcodeToInstruction.put(0x06,x06);
		opcodeToInstruction.put(0x07,x07);
		opcodeToInstruction.put(0x08,x08);
		opcodeToInstruction.put(0x09,x09);
		opcodeToInstruction.put(0x0A,x0A);
		opcodeToInstruction.put(0x0B,x0B);
		opcodeToInstruction.put(0x0C,x0C);
		opcodeToInstruction.put(0x0D,x0D);
		opcodeToInstruction.put(0x0E,x0E);
		opcodeToInstruction.put(0x0F,x0F);
		opcodeToInstruction.put(0x10,x10);
		opcodeToInstruction.put(0x11,x11);
		opcodeToInstruction.put(0x12,x12);
		opcodeToInstruction.put(0x13,x13);
		opcodeToInstruction.put(0x14,x14);
		opcodeToInstruction.put(0x15,x15);
		opcodeToInstruction.put(0x16,x16);
		opcodeToInstruction.put(0x17,x17);
		opcodeToInstruction.put(0x18,x18);
		opcodeToInstruction.put(0x19,x19);
		opcodeToInstruction.put(0x1A,x1A);
		opcodeToInstruction.put(0x1B,x1B);
		opcodeToInstruction.put(0x1C,x1C);
		opcodeToInstruction.put(0x1D,x1D);
		opcodeToInstruction.put(0x1E,x1E);
		opcodeToInstruction.put(0x1F,x1F);
		opcodeToInstruction.put(0x20,x20);
		opcodeToInstruction.put(0x21,x21);
		opcodeToInstruction.put(0x22,x22);
		opcodeToInstruction.put(0x23,x23);
		opcodeToInstruction.put(0x24,x24);
		opcodeToInstruction.put(0x25,x25);
		opcodeToInstruction.put(0x26,x26);
		opcodeToInstruction.put(0x27,x27);
		opcodeToInstruction.put(0x28,x28);
		opcodeToInstruction.put(0x29,x29);
		opcodeToInstruction.put(0x2A,x2A);
		opcodeToInstruction.put(0x2B,x2B);
		opcodeToInstruction.put(0x2C,x2C);
		opcodeToInstruction.put(0x2D,x2D);
		opcodeToInstruction.put(0x2E,x2E);
		opcodeToInstruction.put(0x2F,x2F);
		opcodeToInstruction.put(0x30,x30);
		opcodeToInstruction.put(0x31,x31);
		opcodeToInstruction.put(0x32,x32);
		opcodeToInstruction.put(0x33,x33);
		opcodeToInstruction.put(0x34,x34);
		opcodeToInstruction.put(0x35,x35);
		opcodeToInstruction.put(0x36,x36);
		opcodeToInstruction.put(0x37,x37);
		opcodeToInstruction.put(0x38,x38);
		opcodeToInstruction.put(0x39,x39);
		opcodeToInstruction.put(0x3A,x3A);
		opcodeToInstruction.put(0x3B,x3B);
		opcodeToInstruction.put(0x3C,x3C);
		opcodeToInstruction.put(0x3D,x3D);
		opcodeToInstruction.put(0x3E,x3E);
		opcodeToInstruction.put(0x3F,x3F);
		opcodeToInstruction.put(0x40,x40);
		opcodeToInstruction.put(0x41,x41);
		opcodeToInstruction.put(0x42,x42);
		opcodeToInstruction.put(0x43,x43);
		opcodeToInstruction.put(0x44,x44);
		opcodeToInstruction.put(0x45,x45);
		opcodeToInstruction.put(0x46,x46);
		opcodeToInstruction.put(0x47,x47);
		opcodeToInstruction.put(0x48,x48);
		opcodeToInstruction.put(0x49,x49);
		opcodeToInstruction.put(0x4A,x4A);
		opcodeToInstruction.put(0x4B,x4B);
		opcodeToInstruction.put(0x4C,x4C);
		opcodeToInstruction.put(0x4D,x4D);
		opcodeToInstruction.put(0x4E,x4E);
		opcodeToInstruction.put(0x4F,x4F);
		opcodeToInstruction.put(0x50,x50);
		opcodeToInstruction.put(0x51,x51);
		opcodeToInstruction.put(0x52,x52);
		opcodeToInstruction.put(0x53,x53);
		opcodeToInstruction.put(0x54,x54);
		opcodeToInstruction.put(0x55,x55);
		opcodeToInstruction.put(0x56,x56);
		opcodeToInstruction.put(0x57,x57);
		opcodeToInstruction.put(0x58,x58);
		opcodeToInstruction.put(0x59,x59);
		opcodeToInstruction.put(0x5A,x5A);
		opcodeToInstruction.put(0x5B,x5B);
		opcodeToInstruction.put(0x5C,x5C);
		opcodeToInstruction.put(0x5D,x5D);
		opcodeToInstruction.put(0x5E,x5E);
		opcodeToInstruction.put(0x5F,x5F);
		opcodeToInstruction.put(0x60,x60);
		opcodeToInstruction.put(0x61,x61);
		opcodeToInstruction.put(0x62,x62);
		opcodeToInstruction.put(0x63,x63);
		opcodeToInstruction.put(0x64,x64);
		opcodeToInstruction.put(0x65,x65);
		opcodeToInstruction.put(0x66,x66);
		opcodeToInstruction.put(0x67,x67);
		opcodeToInstruction.put(0x68,x68);
		opcodeToInstruction.put(0x69,x69);
		opcodeToInstruction.put(0x6A,x6A);
		opcodeToInstruction.put(0x6B,x6B);
		opcodeToInstruction.put(0x6C,x6C);
		opcodeToInstruction.put(0x6D,x6D);
		opcodeToInstruction.put(0x6E,x6E);
		opcodeToInstruction.put(0x6F,x6F);
		opcodeToInstruction.put(0x70,x70);
		opcodeToInstruction.put(0x71,x71);
		opcodeToInstruction.put(0x72,x72);
		opcodeToInstruction.put(0x73,x73);
		opcodeToInstruction.put(0x74,x74);
		opcodeToInstruction.put(0x75,x75);
		opcodeToInstruction.put(0x76,x76);
		opcodeToInstruction.put(0x77,x77);
		opcodeToInstruction.put(0x78,x78);
		opcodeToInstruction.put(0x79,x79);
		opcodeToInstruction.put(0x7A,x7A);
		opcodeToInstruction.put(0x7B,x7B);
		opcodeToInstruction.put(0x7C,x7C);
		opcodeToInstruction.put(0x7D,x7D);
		opcodeToInstruction.put(0x7E,x7E);
		opcodeToInstruction.put(0x7F,x7F);
		opcodeToInstruction.put(0x80,x80);
		opcodeToInstruction.put(0x81,x81);
		opcodeToInstruction.put(0x82,x82);
		opcodeToInstruction.put(0x83,x83);
		opcodeToInstruction.put(0x84,x84);
		opcodeToInstruction.put(0x85,x85);
		opcodeToInstruction.put(0x86,x86);
		opcodeToInstruction.put(0x87,x87);
		opcodeToInstruction.put(0x88,x88);
		opcodeToInstruction.put(0x89,x89);
		opcodeToInstruction.put(0x8A,x8A);
		opcodeToInstruction.put(0x8B,x8B);
		opcodeToInstruction.put(0x8C,x8C);
		opcodeToInstruction.put(0x8D,x8D);
		opcodeToInstruction.put(0x8E,x8E);
		opcodeToInstruction.put(0x8F,x8F);
		opcodeToInstruction.put(0x90,x90);
		opcodeToInstruction.put(0x91,x91);
		opcodeToInstruction.put(0x92,x92);
		opcodeToInstruction.put(0x93,x93);
		opcodeToInstruction.put(0x94,x94);
		opcodeToInstruction.put(0x95,x95);
		opcodeToInstruction.put(0x96,x96);
		opcodeToInstruction.put(0x97,x97);
		opcodeToInstruction.put(0x98,x98);
		opcodeToInstruction.put(0x99,x99);
		opcodeToInstruction.put(0x9A,x9A);
		opcodeToInstruction.put(0x9B,x9B);
		opcodeToInstruction.put(0x9C,x9C);
		opcodeToInstruction.put(0x9D,x9D);
		opcodeToInstruction.put(0x9E,x9E);
		opcodeToInstruction.put(0x9F,x9F);
		opcodeToInstruction.put(0xA0,xA0);
		opcodeToInstruction.put(0xA1,xA1);
		opcodeToInstruction.put(0xA2,xA2);
		opcodeToInstruction.put(0xA3,xA3);
		opcodeToInstruction.put(0xA4,xA4);
		opcodeToInstruction.put(0xA5,xA5);
		opcodeToInstruction.put(0xA6,xA6);
		opcodeToInstruction.put(0xA7,xA7);
		opcodeToInstruction.put(0xA8,xA8);
		opcodeToInstruction.put(0xA9,xA9);
		opcodeToInstruction.put(0xAA,xAA);
		opcodeToInstruction.put(0xAB,xAB);
		opcodeToInstruction.put(0xAC,xAC);
		opcodeToInstruction.put(0xAD,xAD);
		opcodeToInstruction.put(0xAE,xAE);
		opcodeToInstruction.put(0xAF,xAF);
		opcodeToInstruction.put(0xB0,xB0);
		opcodeToInstruction.put(0xB1,xB1);
		opcodeToInstruction.put(0xB2,xB2);
		opcodeToInstruction.put(0xB3,xB3);
		opcodeToInstruction.put(0xB4,xB4);
		opcodeToInstruction.put(0xB5,xB5);
		opcodeToInstruction.put(0xB6,xB6);
		opcodeToInstruction.put(0xB7,xB7);
		opcodeToInstruction.put(0xB8,xB8);
		opcodeToInstruction.put(0xB9,xB9);
		opcodeToInstruction.put(0xBA,xBA);
		opcodeToInstruction.put(0xBB,xBB);
		opcodeToInstruction.put(0xBC,xBC);
		opcodeToInstruction.put(0xBD,xBD);
		opcodeToInstruction.put(0xBE,xBE);
		opcodeToInstruction.put(0xBF,xBF);
		opcodeToInstruction.put(0xC0,xC0);
		opcodeToInstruction.put(0xC1,xC1);
		opcodeToInstruction.put(0xC2,xC2);
		opcodeToInstruction.put(0xC3,xC3);
		opcodeToInstruction.put(0xC4,xC4);
		opcodeToInstruction.put(0xC5,xC5);
		opcodeToInstruction.put(0xC6,xC6);
		opcodeToInstruction.put(0xC7,xC7);
		opcodeToInstruction.put(0xC8,xC8);
		opcodeToInstruction.put(0xC9,xC9);
		opcodeToInstruction.put(0xCA,xCA);
		opcodeToInstruction.put(0xCC,xCC);
		opcodeToInstruction.put(0xCD,xCD);
		opcodeToInstruction.put(0xCE,xCE);
		opcodeToInstruction.put(0xCF,xCF);
		opcodeToInstruction.put(0xD0,xD0);
		opcodeToInstruction.put(0xD1,xD1);
		opcodeToInstruction.put(0xD2,xD2);
		opcodeToInstruction.put(0xD4,xD4);
		opcodeToInstruction.put(0xD5,xD5);
		opcodeToInstruction.put(0xD6,xD6);
		opcodeToInstruction.put(0xD7,xD7);
		opcodeToInstruction.put(0xD8,xD8);
		opcodeToInstruction.put(0xD9,xD9);
		opcodeToInstruction.put(0xDA,xDA);
		opcodeToInstruction.put(0xDC,xDC);
		opcodeToInstruction.put(0xDE,xDE);
		opcodeToInstruction.put(0xDF,xDF);
		opcodeToInstruction.put(0xE0,xE0);
		opcodeToInstruction.put(0xE1,xE1);
		opcodeToInstruction.put(0xE2,xE2);
		opcodeToInstruction.put(0xE5,xE5);
		opcodeToInstruction.put(0xE6,xE6);
		opcodeToInstruction.put(0xE7,xE7);
		opcodeToInstruction.put(0xE8,xE8);
		opcodeToInstruction.put(0xE9,xE9);
		opcodeToInstruction.put(0xEA,xEA);
		opcodeToInstruction.put(0xEE,xEE);
		opcodeToInstruction.put(0xEF,xEF);
		opcodeToInstruction.put(0xF0,xF0);
		opcodeToInstruction.put(0xF1,xF1);
		opcodeToInstruction.put(0xF2,xF2);
		opcodeToInstruction.put(0xF3,xF3);
		opcodeToInstruction.put(0xF5,xF5);
		opcodeToInstruction.put(0xF6,xF6);
		opcodeToInstruction.put(0xF7,xF7);
		opcodeToInstruction.put(0xF8,xF8);
		opcodeToInstruction.put(0xF9,xF9);
		opcodeToInstruction.put(0xFA,xFA);
		opcodeToInstruction.put(0xFB,xFB);
		opcodeToInstruction.put(0xFE,xFE);
		opcodeToInstruction.put(0xFF,xFF);
		opcodeToInstruction.put(0xDE00,xDE00);
		opcodeToInstruction.put(0xDE01,xDE01);
		opcodeToInstruction.put(0xDE02,xDE02);
		opcodeToInstruction.put(0xDE03,xDE03);
		opcodeToInstruction.put(0xDE04,xDE04);
		opcodeToInstruction.put(0xCB00,xCB00);
		opcodeToInstruction.put(0xCB01,xCB01);
		opcodeToInstruction.put(0xCB02,xCB02);
		opcodeToInstruction.put(0xCB03,xCB03);
		opcodeToInstruction.put(0xCB04,xCB04);
		opcodeToInstruction.put(0xCB05,xCB05);
		opcodeToInstruction.put(0xCB06,xCB06);
		opcodeToInstruction.put(0xCB07,xCB07);
		opcodeToInstruction.put(0xCB08,xCB08);
		opcodeToInstruction.put(0xCB09,xCB09);
		opcodeToInstruction.put(0xCB0A,xCB0A);
		opcodeToInstruction.put(0xCB0B,xCB0B);
		opcodeToInstruction.put(0xCB0C,xCB0C);
		opcodeToInstruction.put(0xCB0D,xCB0D);
		opcodeToInstruction.put(0xCB0E,xCB0E);
		opcodeToInstruction.put(0xCB0F,xCB0F);
		opcodeToInstruction.put(0xCB10,xCB10);
		opcodeToInstruction.put(0xCB11,xCB11);
		opcodeToInstruction.put(0xCB12,xCB12);
		opcodeToInstruction.put(0xCB13,xCB13);
		opcodeToInstruction.put(0xCB14,xCB14);
		opcodeToInstruction.put(0xCB15,xCB15);
		opcodeToInstruction.put(0xCB16,xCB16);
		opcodeToInstruction.put(0xCB17,xCB17);
		opcodeToInstruction.put(0xCB18,xCB18);
		opcodeToInstruction.put(0xCB19,xCB19);
		opcodeToInstruction.put(0xCB1A,xCB1A);
		opcodeToInstruction.put(0xCB1B,xCB1B);
		opcodeToInstruction.put(0xCB1C,xCB1C);
		opcodeToInstruction.put(0xCB1D,xCB1D);
		opcodeToInstruction.put(0xCB1E,xCB1E);
		opcodeToInstruction.put(0xCB1F,xCB1F);
		opcodeToInstruction.put(0xCB20,xCB20);
		opcodeToInstruction.put(0xCB21,xCB21);
		opcodeToInstruction.put(0xCB22,xCB22);
		opcodeToInstruction.put(0xCB23,xCB23);
		opcodeToInstruction.put(0xCB24,xCB24);
		opcodeToInstruction.put(0xCB25,xCB25);
		opcodeToInstruction.put(0xCB26,xCB26);
		opcodeToInstruction.put(0xCB27,xCB27);
		opcodeToInstruction.put(0xCB28,xCB28);
		opcodeToInstruction.put(0xCB29,xCB29);
		opcodeToInstruction.put(0xCB2A,xCB2A);
		opcodeToInstruction.put(0xCB2B,xCB2B);
		opcodeToInstruction.put(0xCB2C,xCB2C);
		opcodeToInstruction.put(0xCB2D,xCB2D);
		opcodeToInstruction.put(0xCB2E,xCB2E);
		opcodeToInstruction.put(0xCB2F,xCB2F);
		opcodeToInstruction.put(0xCB30,xCB30);
		opcodeToInstruction.put(0xCB31,xCB31);
		opcodeToInstruction.put(0xCB32,xCB32);
		opcodeToInstruction.put(0xCB33,xCB33);
		opcodeToInstruction.put(0xCB34,xCB34);
		opcodeToInstruction.put(0xCB35,xCB35);
		opcodeToInstruction.put(0xCB36,xCB36);
		opcodeToInstruction.put(0xCB37,xCB37);
		opcodeToInstruction.put(0xCB38,xCB38);
		opcodeToInstruction.put(0xCB39,xCB39);
		opcodeToInstruction.put(0xCB3A,xCB3A);
		opcodeToInstruction.put(0xCB3B,xCB3B);
		opcodeToInstruction.put(0xCB3C,xCB3C);
		opcodeToInstruction.put(0xCB3D,xCB3D);
		opcodeToInstruction.put(0xCB3E,xCB3E);
		opcodeToInstruction.put(0xCB3F,xCB3F);
		opcodeToInstruction.put(0xCB40,xCB40);
		opcodeToInstruction.put(0xCB41,xCB41);
		opcodeToInstruction.put(0xCB42,xCB42);
		opcodeToInstruction.put(0xCB43,xCB43);
		opcodeToInstruction.put(0xCB44,xCB44);
		opcodeToInstruction.put(0xCB45,xCB45);
		opcodeToInstruction.put(0xCB46,xCB46);
		opcodeToInstruction.put(0xCB47,xCB47);
		opcodeToInstruction.put(0xCB48,xCB48);
		opcodeToInstruction.put(0xCB49,xCB49);
		opcodeToInstruction.put(0xCB4A,xCB4A);
		opcodeToInstruction.put(0xCB4B,xCB4B);
		opcodeToInstruction.put(0xCB4C,xCB4C);
		opcodeToInstruction.put(0xCB4D,xCB4D);
		opcodeToInstruction.put(0xCB4E,xCB4E);
		opcodeToInstruction.put(0xCB4F,xCB4F);
		opcodeToInstruction.put(0xCB50,xCB50);
		opcodeToInstruction.put(0xCB51,xCB51);
		opcodeToInstruction.put(0xCB52,xCB52);
		opcodeToInstruction.put(0xCB53,xCB53);
		opcodeToInstruction.put(0xCB54,xCB54);
		opcodeToInstruction.put(0xCB55,xCB55);
		opcodeToInstruction.put(0xCB56,xCB56);
		opcodeToInstruction.put(0xCB57,xCB57);
		opcodeToInstruction.put(0xCB58,xCB58);
		opcodeToInstruction.put(0xCB59,xCB59);
		opcodeToInstruction.put(0xCB5A,xCB5A);
		opcodeToInstruction.put(0xCB5B,xCB5B);
		opcodeToInstruction.put(0xCB5C,xCB5C);
		opcodeToInstruction.put(0xCB5D,xCB5D);
		opcodeToInstruction.put(0xCB5E,xCB5E);
		opcodeToInstruction.put(0xCB5F,xCB5F);
		opcodeToInstruction.put(0xCB60,xCB60);
		opcodeToInstruction.put(0xCB61,xCB61);
		opcodeToInstruction.put(0xCB62,xCB62);
		opcodeToInstruction.put(0xCB63,xCB63);
		opcodeToInstruction.put(0xCB64,xCB64);
		opcodeToInstruction.put(0xCB65,xCB65);
		opcodeToInstruction.put(0xCB66,xCB66);
		opcodeToInstruction.put(0xCB67,xCB67);
		opcodeToInstruction.put(0xCB68,xCB68);
		opcodeToInstruction.put(0xCB69,xCB69);
		opcodeToInstruction.put(0xCB6A,xCB6A);
		opcodeToInstruction.put(0xCB6B,xCB6B);
		opcodeToInstruction.put(0xCB6C,xCB6C);
		opcodeToInstruction.put(0xCB6D,xCB6D);
		opcodeToInstruction.put(0xCB6E,xCB6E);
		opcodeToInstruction.put(0xCB6F,xCB6F);
		opcodeToInstruction.put(0xCB70,xCB70);
		opcodeToInstruction.put(0xCB71,xCB71);
		opcodeToInstruction.put(0xCB72,xCB72);
		opcodeToInstruction.put(0xCB73,xCB73);
		opcodeToInstruction.put(0xCB74,xCB74);
		opcodeToInstruction.put(0xCB75,xCB75);
		opcodeToInstruction.put(0xCB76,xCB76);
		opcodeToInstruction.put(0xCB77,xCB77);
		opcodeToInstruction.put(0xCB78,xCB78);
		opcodeToInstruction.put(0xCB79,xCB79);
		opcodeToInstruction.put(0xCB7A,xCB7A);
		opcodeToInstruction.put(0xCB7B,xCB7B);
		opcodeToInstruction.put(0xCB7C,xCB7C);
		opcodeToInstruction.put(0xCB7D,xCB7D);
		opcodeToInstruction.put(0xCB7E,xCB7E);
		opcodeToInstruction.put(0xCB7F,xCB7F);
		opcodeToInstruction.put(0xCB80,xCB80);
		opcodeToInstruction.put(0xCB81,xCB81);
		opcodeToInstruction.put(0xCB82,xCB82);
		opcodeToInstruction.put(0xCB83,xCB83);
		opcodeToInstruction.put(0xCB84,xCB84);
		opcodeToInstruction.put(0xCB85,xCB85);
		opcodeToInstruction.put(0xCB86,xCB86);
		opcodeToInstruction.put(0xCB87,xCB87);
		opcodeToInstruction.put(0xCB88,xCB88);
		opcodeToInstruction.put(0xCB89,xCB89);
		opcodeToInstruction.put(0xCB8A,xCB8A);
		opcodeToInstruction.put(0xCB8B,xCB8B);
		opcodeToInstruction.put(0xCB8C,xCB8C);
		opcodeToInstruction.put(0xCB8D,xCB8D);
		opcodeToInstruction.put(0xCB8E,xCB8E);
		opcodeToInstruction.put(0xCB8F,xCB8F);
		opcodeToInstruction.put(0xCB90,xCB90);
		opcodeToInstruction.put(0xCB91,xCB91);
		opcodeToInstruction.put(0xCB92,xCB92);
		opcodeToInstruction.put(0xCB93,xCB93);
		opcodeToInstruction.put(0xCB94,xCB94);
		opcodeToInstruction.put(0xCB95,xCB95);
		opcodeToInstruction.put(0xCB96,xCB96);
		opcodeToInstruction.put(0xCB97,xCB97);
		opcodeToInstruction.put(0xCB98,xCB98);
		opcodeToInstruction.put(0xCB99,xCB99);
		opcodeToInstruction.put(0xCB9A,xCB9A);
		opcodeToInstruction.put(0xCB9B,xCB9B);
		opcodeToInstruction.put(0xCB9C,xCB9C);
		opcodeToInstruction.put(0xCB9D,xCB9D);
		opcodeToInstruction.put(0xCB9E,xCB9E);
		opcodeToInstruction.put(0xCB9F,xCB9F);
		opcodeToInstruction.put(0xCBA0,xCBA0);
		opcodeToInstruction.put(0xCBA1,xCBA1);
		opcodeToInstruction.put(0xCBA2,xCBA2);
		opcodeToInstruction.put(0xCBA3,xCBA3);
		opcodeToInstruction.put(0xCBA4,xCBA4);
		opcodeToInstruction.put(0xCBA5,xCBA5);
		opcodeToInstruction.put(0xCBA6,xCBA6);
		opcodeToInstruction.put(0xCBA7,xCBA7);
		opcodeToInstruction.put(0xCBA8,xCBA8);
		opcodeToInstruction.put(0xCBA9,xCBA9);
		opcodeToInstruction.put(0xCBAA,xCBAA);
		opcodeToInstruction.put(0xCBAB,xCBAB);
		opcodeToInstruction.put(0xCBAC,xCBAC);
		opcodeToInstruction.put(0xCBAD,xCBAD);
		opcodeToInstruction.put(0xCBAE,xCBAE);
		opcodeToInstruction.put(0xCBAF,xCBAF);
		opcodeToInstruction.put(0xCBB0,xCBB0);
		opcodeToInstruction.put(0xCBB1,xCBB1);
		opcodeToInstruction.put(0xCBB2,xCBB2);
		opcodeToInstruction.put(0xCBB3,xCBB3);
		opcodeToInstruction.put(0xCBB4,xCBB4);
		opcodeToInstruction.put(0xCBB5,xCBB5);
		opcodeToInstruction.put(0xCBB6,xCBB6);
		opcodeToInstruction.put(0xCBB7,xCBB7);
		opcodeToInstruction.put(0xCBB8,xCBB8);
		opcodeToInstruction.put(0xCBB9,xCBB9);
		opcodeToInstruction.put(0xCBBA,xCBBA);
		opcodeToInstruction.put(0xCBBB,xCBBB);
		opcodeToInstruction.put(0xCBBC,xCBBC);
		opcodeToInstruction.put(0xCBBD,xCBBD);
		opcodeToInstruction.put(0xCBBE,xCBBE);
		opcodeToInstruction.put(0xCBBF,xCBBF);
		opcodeToInstruction.put(0xCBC0,xCBC0);
		opcodeToInstruction.put(0xCBC1,xCBC1);
		opcodeToInstruction.put(0xCBC2,xCBC2);
		opcodeToInstruction.put(0xCBC3,xCBC3);
		opcodeToInstruction.put(0xCBC4,xCBC4);
		opcodeToInstruction.put(0xCBC5,xCBC5);
		opcodeToInstruction.put(0xCBC6,xCBC6);
		opcodeToInstruction.put(0xCBC7,xCBC7);
		opcodeToInstruction.put(0xCBC8,xCBC8);
		opcodeToInstruction.put(0xCBC9,xCBC9);
		opcodeToInstruction.put(0xCBCA,xCBCA);
		opcodeToInstruction.put(0xCBCB,xCBCB);
		opcodeToInstruction.put(0xCBCC,xCBCC);
		opcodeToInstruction.put(0xCBCD,xCBCD);
		opcodeToInstruction.put(0xCBCE,xCBCE);
		opcodeToInstruction.put(0xCBCF,xCBCF);
		opcodeToInstruction.put(0xCBD0,xCBD0);
		opcodeToInstruction.put(0xCBD1,xCBD1);
		opcodeToInstruction.put(0xCBD2,xCBD2);
		opcodeToInstruction.put(0xCBD3,xCBD3);
		opcodeToInstruction.put(0xCBD4,xCBD4);
		opcodeToInstruction.put(0xCBD5,xCBD5);
		opcodeToInstruction.put(0xCBD6,xCBD6);
		opcodeToInstruction.put(0xCBD7,xCBD7);
		opcodeToInstruction.put(0xCBD8,xCBD8);
		opcodeToInstruction.put(0xCBD9,xCBD9);
		opcodeToInstruction.put(0xCBDA,xCBDA);
		opcodeToInstruction.put(0xCBDB,xCBDB);
		opcodeToInstruction.put(0xCBDC,xCBDC);
		opcodeToInstruction.put(0xCBDD,xCBDD);
		opcodeToInstruction.put(0xCBDE,xCBDE);
		opcodeToInstruction.put(0xCBDF,xCBDF);
		opcodeToInstruction.put(0xCBE0,xCBE0);
		opcodeToInstruction.put(0xCBE1,xCBE1);
		opcodeToInstruction.put(0xCBE2,xCBE2);
		opcodeToInstruction.put(0xCBE3,xCBE3);
		opcodeToInstruction.put(0xCBE4,xCBE4);
		opcodeToInstruction.put(0xCBE5,xCBE5);
		opcodeToInstruction.put(0xCBE6,xCBE6);
		opcodeToInstruction.put(0xCBE7,xCBE7);
		opcodeToInstruction.put(0xCBE8,xCBE8);
		opcodeToInstruction.put(0xCBE9,xCBE9);
		opcodeToInstruction.put(0xCBEA,xCBEA);
		opcodeToInstruction.put(0xCBEB,xCBEB);
		opcodeToInstruction.put(0xCBEC,xCBEC);
		opcodeToInstruction.put(0xCBED,xCBED);
		opcodeToInstruction.put(0xCBEE,xCBEE);
		opcodeToInstruction.put(0xCBEF,xCBEF);
		opcodeToInstruction.put(0xCBF0,xCBF0);
		opcodeToInstruction.put(0xCBF1,xCBF1);
		opcodeToInstruction.put(0xCBF2,xCBF2);
		opcodeToInstruction.put(0xCBF3,xCBF3);
		opcodeToInstruction.put(0xCBF4,xCBF4);
		opcodeToInstruction.put(0xCBF5,xCBF5);
		opcodeToInstruction.put(0xCBF6,xCBF6);
		opcodeToInstruction.put(0xCBF7,xCBF7);
		opcodeToInstruction.put(0xCBF8,xCBF8);
		opcodeToInstruction.put(0xCBF9,xCBF9);
		opcodeToInstruction.put(0xCBFA,xCBFA);
		opcodeToInstruction.put(0xCBFB,xCBFB);
		opcodeToInstruction.put(0xCBFC,xCBFC);
		opcodeToInstruction.put(0xCBFD,xCBFD);
		opcodeToInstruction.put(0xCBFE,xCBFE);
		opcodeToInstruction.put(0xCBFF,xCBFF);

		
	}
}
